[alembic]
# マイグレーションファイルの置き場所
script_location = alembic

# マイグレーションファイルの命名規則: 例）0001_create_initial_tables.py
file_template = %%(rev)s_%%(slug)s

# sqlalchemy.url はここでは設定しない
# → alembic/env.py で DATABASE_URL 環境変数から取得する

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
